proyecto1/config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  get 'event/get_location'
  get 'event/store'
  root :to => 'inicio#index'
  get 'event/map'
  get 'event/date'

#Entra a la carpeta creada "api" se va a manejar por jason
    namespace :api, default: {format: 'json'} do

  	resources :location, only: [:create]
  	
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

proyecto1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

proyecto1/app/models/event.rb
class Event < ApplicationRecord
end

proyecto1/app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         #Crea un TOKEN unico para cada usuario creado en la BD	
         before_create -> {self.token = generate_token}

    private
    def generate_token
 	
    	loop do 
    		 
    		 token = SecureRandom.hex
    		 return token unless Usuario.exists?({token: token})
    		
    	end
    end
end

proyecto1/app/controllers/api/location_controller.rb
class Api::LocationController < ApplicationController

	skip_before_action :verify_authenticity_token
  #Metodo para uno mismo autenticar :)

	def create
        #El jason llega con los siguientes metodos y se separa la informacion.

       token = params[:token]
  	   latitude = params[:latitude]
  	   longitude = params[:longitude]
  	   user = params[:user]
  	   @event = Event.new(user: user, y: latitude, x: longitude)
        #Si el usuario que usa la API tiene un TOKEN valido almacena el evento en BD
  	   if (token == Usuario.find(user).token) and @event.save

  	   		render json: @event, status: :created

  	   	else

  	   		render json: @event.errors, status: :unprocessable_entity

  	   end

	end

	private

	def location_params
     #Metodo especial de reails que solo puede recibir estos parametros. 
		params.require(:user, :token).permit(:latitude, :longitude, :user, :token)

	end


end

proyecto1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

proyecto1/app/controllers/event_controller.rb
class EventController < ApplicationController
  def get_location
  	@location = Event.last(10)
end

def store
	respond_to do |format|

		latitude = params[:latitude]
		longitude = params[:longitude]

		@event = Event.new(user: current_usuario.id, x: longitude, y: latitude)

		if @event.save then 

			
            url = request.original_url.sub("http", "https")
            url = url.sub("store", "get_location")
  		   	format.html{redirect_to url}

		else

			flash[:notice_booking_fail] =  true 
			redirect_to event_get_location_path
		end	
	end	


  end

def map
	@starting_date = params[:starting][:date_1]
	@ending_date = params[:ending][:date_2]
	@usuario_events = Event.where(user: current_usuario.id)
	@result = Array.new

	@usuario_events.each do |event|

		 if((event.created_at.to_time >= @starting_date.to_time) && 
        (event.created_at.to_time <= @ending_date.to_time)) then

        @result << event
    	end
    end


	@link = "https://www.google.es/maps/dir/" 

	@result.each do |coords|

		 @link.concat("'" + coords.y.to_s + "," + coords.x.to_s + "'" + "/")

	end
	
	redirect_to @link

end

def date

end


end

proyecto1/app/controllers/inicio_controller.rb
class InicioController < ApplicationController
def index  
      @url = request.original_url.sub("http", "https")
      @url = @url.concat("event/get_location")
   end

end

proyecto1/app/helpers/application_helper.rb
module ApplicationHelper
end

proyecto1/app/helpers/event_helper.rb
module EventHelper
end

proyecto1/app/helpers/inicio_helper.rb
module InicioHelper
end

proyecto1/app/views/event/date.html.erb
<body>
	
	<%= form_tag("/event/map", method: "get") do %>
	<%= label_tag(:starting, "Starting Date") %>
	<%= datetime_local_field(:starting, :date_1) %>
	<%= label_tag(:ending, "Ending Date") %>
	<%= datetime_local_field(:ending, :date_2) %>
	<%= submit_tag("Next") %>
	<%end%>

	<%= link_to "back", root_path, :method => :get %>
	
</body>

proyecto1/app/views/event/get_location.html.erb
<body>
	<script>
	function getlocation (){
		if(navigator.geolocation){
			navigator.geolocation.getCurrentPosition(storePosition);
		} else{
			document.write("El geolocalizador no es soportado por el navigator");
		} 
	}
	function getposition (position){
		document.write("Latitud:" + position.coords.latitude + "<br>Longitud: " + position.coords.longitude);
}

	function storePosition(position){
        
        var original_url = window.location.href;
        var store_url = "store?latitude=" + position.coords.latitude +
		"&longitude=" + position.coords.longitude;
        var url = original_url.slice(0,original_url.indexOf("get_location")) + store_url;
	window.open(url, "_self");
  
}
	window.setInterval(getlocation,1000);

	</script>

<% while !@location.empty? %>
        <% coordinate = @location.pop %>
        <br><h3> Coordinate <%= coordinate.id %> </h3>
        <ul>
        	<li> <b>UserId:</b> <%= coordinate.user %></li>
        	<li> <b>Latitude:</b> <%= coordinate.y %></li>
        	<li> <b>Longitude:</b> <%= coordinate.x %></li>
        </ul>
	<% end %>

</body>

proyecto1/app/views/event/map.html.erb
<body>

</body>

proyecto1/app/views/inicio/index.html.erb
<% if usuario_signed_in? %>

<h3>you have succesfully signed in</h3>
<%= link_to "Sign Out", destroy_usuario_session_path, :method => :delete %>
<%= link_to "Siguiente", @url, :method => :get %>
<%= link_to "Mapa", event_date_path, :method => :get %>


<% else %>

<h1> welcom to rails community</h1>
<%= link_to "Sign In", new_usuario_session_path, :method => :get %>
<%= link_to "Sign up", new_usuario_registration_path, :method => :get %>

<% end %>

proyecto1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyecto1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>